STATES = [
    # Базовые состояния
    "START", "CHOOSE_ROLE", "STUDENT_MAIN", "TEACHER_MAIN",
    
    # Ученик: прохождение теста
    "STUDENT_SELECT_SUBJECT", "STUDENT_SELECT_CLASS", "STUDENT_ENTER_TEST_NAME",
    "STUDENT_SELECT_TEST", "STUDENT_ENTER_INFO", "STUDENT_TEST_INSTRUCTIONS",
    "STUDENT_ANSWER_QUESTIONS", "STUDENT_REVIEW_ANSWERS", "STUDENT_TEST_RESULTS",
    "STUDENT_APPEAL", "STUDENT_APPEAL_COMMENT", "STUDENT_APPEAL_SELECT",
    
    # Ученик: просмотр результатов
    "STUDENT_SELECT_RESULT_SUBJECT", "STUDENT_SELECT_RESULT_CLASS", "STUDENT_VIEW_RESULTS", 
    "STUDENT_VIEW_TEST_DETAILS", "STUDENT_ENTER_RESULT_NAME", "STUDENT_SELECT_RESULT_TEST",
    "STUDENT_VIEW_RESULT_DETAILS", "STUDENT_VIEW_QUESTION_DETAILS",
    
    # Учитель: создание теста
    "TEACHER_SELECT_SUBJECT", "TEACHER_SELECT_CLASS", "TEACHER_ENTER_NAME",
    "TEACHER_QUESTION_TYPE", "TEACHER_ENTER_QUESTION", "TEACHER_ENTER_CORRECT_ANSWER",
    "TEACHER_ADD_OPTIONS", "TEACHER_ADD_COMMENT", "TEACHER_FINISH_CREATION",
    "TEACHER_GLOBAL_COMMENT", "TEACHER_EDIT_QUESTIONS", "TEACHER_EDIT_QUESTION_PART",
    "TEACHER_EDIT_QUESTION_CONTENT", "TEACHER_FINAL_EDIT", "TEACHER_FINAL_CONFIRM",
    "TEACHER_EDIT_SUBJECT", "TEACHER_EDIT_CLASSES", "TEACHER_EDIT_GLOBAL_COMMENT",
    
    # Учитель: проверка работ
    "TEACHER_CHECK_RESULTS",        # Начало проверки (список тестов)
    "TEACHER_CHECK_TEST",          # Выбор режима анализа теста
    "TEACHER_CHECK_STUDENTS",      # Статистика по ученикам
    "TEACHER_CHECK_QUESTIONS",     # Статистика по вопросам
    "TEACHER_CHECK_ANSWERS",       # Ответы на вопрос
    "TEACHER_EDIT_ANSWER",         # Редактирование ответа/апелляции
    "TEACHER_CHECK_APPEALS",       # Просмотр апелляций
    "TEACHER_RESPOND_APPEAL",       # Ответ на апелляцию
    "TEACHER_EDIT_SCORE",
    "TEACHER_VIEW_STUDENT_QUESTIONS",
    "TEACHER_ADD_COMMENT",
    "TEACHER_EDIT_SCORE_APPEAL",  # Новое состояние
    "TEACHER_ADD_COMMENT_APPEAL",
    "TEACHER_VIEW_QUESTION_ANSWERS"
]

# Автоматическая генерация констант
states_enum = {state: idx for idx, state in enumerate(STATES)}
globals().update(states_enum)